# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo git clone https://github.com/nityanand86876/python_hcf.git
        cd python_hcf
        sudo curl -s https://install.speedtest.net/app/cli/install.deb.sh | sudo bash && sudo apt-get install speedtest && speedtest --accept-license
        python find_hcf.py
        python find_hcf.py
        python find_hcf.py
        python find_hcf.py
        python find_hcf.py
        python find_hcf.py
        python find_hcf.py
        python find_hcf.py
      

